### ISSUE TITLE
{{blockTime}} not loaded in primer

### ISSUE THREAD

**Issue by mongolsteppe** [livepeer/livepeer-org#147]
See pic below
![image](https://user-images.githubusercontent.com/75075420/127386724-174adf36-b704-48cc-9156-955ea3e8fbf0.png)

You can find the primer json [here](https://github.com/livepeer/livepeer-org/blob/master/public/locales/en/primer.json) and the blockTime variable stems from [here](https://github.com/livepeer/livepeer-org/blob/master/components/sections/primer/Chapter8/index.tsx)

**Comment by adamsoffer** [comment]
Thanks for pointing this out @mongolsteppe !
