### ISSUE TITLE
Video Application Developer - Reference

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-org#47]

**Comment by adamsoffer** [comment]
- [ ] Livepeer CLI command reference

**Comment by yondonfu** [comment]
Could just add links to the go-livepeer docs related to broadcaster focused references

**Comment by yondonfu** [comment]
@wohlner to make sure HTTP push API go-livepeer docs are up-to-date.

**Comment by wohlner** [comment]
The HTTP push docs will need to be written from scratch. The existing one use a Livepeer.com API key and endpoints. Let's scrap this for the MVP. cc: @yondonfu @adamsoffer

**Comment by wohlner** [comment]
Sorry, I misunderstood the comment from March 4. I'll take a look at https://github.com/livepeer/go-livepeer/blob/master/doc/ingest.md#http-push

**Comment by wohlner** [comment]
New plan: write a "preamble" in the video developers section of .org and link to the github ingest.md above

**Comment by wohlner** [comment]
https://github.com/livepeer/livepeer-org/tree/jb/docs/docs/video-developers/reference
