### ISSUE TITLE
Video Application Developer - Overview

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-org#48]

**Comment by wohlner** [comment]
Here's the copy. https://github.com/livepeer/livepeer-org/blob/docs/docs/developers/index.md

**Comment by adamsoffer** [comment]
@wohlner woot! This looks great.

**Comment by wohlner** [comment]
There's some confusion about which input formats allow for which output video formats. I'm sorting it out in a discord and will tweak the docs as appropriate.
