### ISSUE TITLE
Video Miners - How-to Guides

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-org#52]

**Comment by adamsoffer** [comment]
- [ ] How to connect your orchestrator to remote transcoders
- [ ] How to benchmark transcoding
- [ ] How to set up transcoder monitoring with Prometheus & Grafana 
- [ ] How to set session limits
- [ ] How to calculate estimated profits
- [ ] How to dual mine
- [ ] Troubleshooting

**Comment by yondonfu** [comment]
Closed by #64
