### ISSUE TITLE
Video Miners - Core Concepts

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-org#53]

**Comment by adamsoffer** [comment]
- [ ] How video mining works
- [ ] Roles: orchestrators and transcoders
- [ ] Transcoding pools
- [ ] What makes a successful video miner?
- [ ] What is dual mining?

**Comment by yondonfu** [comment]
Add "How to think about revenue/profits" - reference on the things to consider when thinking about generating revenue on the network

**Comment by yondonfu** [comment]
Closed by #67
