### ISSUE TITLE
Fix cost to activate node number on video miners page

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-org#80]
https://livepeer.org/video-miners shows the cost to activate a node as free, but this isn't quite true and has caused some confusion amongst node operators since activation for an orchestrator does require ETH transaction fees. Maybe there is an argument for saying its free if you're running a transcoder as a part of a pool, but that distinction is not made here. The wording here should be updated so that at the very least users do not think that activating an orchestrator is completely free.

**Comment by adamsoffer** [comment]
Thoughts on replacing "free" with the total amount of gas in ETH it costs to activate?

**Comment by yondonfu** [comment]
What about "Minutes of video transcoded"?

**Comment by adamsoffer** [comment]
Nice one 👍
